version: "3.1"

services:
  mysql:
    image: mysql:latest
    container_name: meu-banco-mysql
    environment:
      MYSQL_ROOT_PASSWORD: sua_senha_root
      MYSQL_DATABASE: sua_base_de_dados
      MYSQL_USER: seu_usuario
      MYSQL_PASSWORD: sua_senha
    ports:
      - "3306:3306"
    volumes:
      - ./dados_mysql:/var/lib/mysql
